### ISSUE TITLE
Please add LocalPlayer_TypeInfo offset.

### ISSUE THREAD

**Issue by itsRythem** [Akandesh/BlazeDumper-Rust#10]

**Comment by Akandesh** [comment]
dumper is offline for the time being, need to get my cheat working before I do any work with it. 

here's LocalPlayer tho

```
    {
      "Address": 63394640,
      "Name": "%6b1d1ed063be1917a35cc7ac3404edcdf1725506_TypeInfo",
      "Signature": "_6b1d1ed063be1917a35cc7ac3404edcdf1725506_c*"
    },
```

**Comment by peiga** [comment]
Please keep us updated @Akandesh :)

**Comment by CoinflipADC** [comment]
We need you more than ever but do you really think dumper can be made for this update? Is this possible? What you think?

**Comment by Akandesh** [comment]
I'll see if I can get something working today, won't be anything amazing but will try to do some regex magic to atleast get some classes working but fields will still have random names. 

@CoinflipADC I'm not sure, depends on how powerful signatures can get but we'll see.

**Comment by peiga** [comment]
> I'll see if I can get something working today, won't be anything amazing but will try to do some regex magic to atleast get some classes working but fields will still have random names.
> 
> @CoinflipADC I'm not sure, depends on how powerful signatures can get but we'll see.

Thanks for the effort, I'll be watching out for updates

**Comment by Akandesh** [comment]
> Thanks for the update 🥳 For now its not understandable but if you know what are theese namespace && classes they can be manuel named in algorithm For example if(sign == 48 ? 65 xx xx) add.info("localplayer_c"); But i dont know if it possible in your dumper. Thank you for trying to improve 🫡.

Not sure what you mean. I could manually rename the encrypted classes etc to their proper names but since this automatically dumps when there's a new update it has to know everything beforehand. 

I suppose I could make a system that allows users to rename certain encrypted items through a webpage and then automatically have it rerun the program and push to github but that could end up being a waste of time. 

I activated Discussions so we can ball ideas there instead. https://github.com/Akandesh/BlazeDumper-Rust/discussions/categories/ideas
