### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by CodecNomad** [Akandesh/BlazeDumper-Rust#12]

**Comment by Akandesh** [comment]
yep, something broke

**Comment by Akandesh** [comment]
fixed, seems like they moved the class order around in dump.cs which made a optimization fail and after that I was unable to push it because the files are too large for github so had to compress the dump.cs, il2cpp.h and script.json so gotta write some code to do that automatically but right now I'm in recovery after a procedure so not energy for this.
